pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'gradle assemble'
            }
        }
 //       stage('Test') {
 //          steps {
 //               sh 'gradle test'
//            }
 //       }
        stage('Build Docker image') {
            steps {
                bat 'gradle docker'
            }
        }
        stage('Run Docker Image') {
            steps {
                bat 'gradle dockerRun'
            }
        }
    }
}
