pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/opt/gradle/gradle-6.5.1/bin/gradle assemble'
            }
        }
 //       stage('Test') {
 //          steps {
 //               sh 'gradle test'
//            }
 //       }
        stage('Build Docker image') {
            steps {
                sh '/opt/gradle/gradle-6.5.1/bin/gradle docker'
            }
        }
        stage('Run Docker Image') {
            steps {
                sh '/opt/gradle/gradle-6.5.1/bin/gradle dockerRun'
            }
        }
    }
}
